name: website
on:
  push:
    branches:
      - master
  workflow_dispatch:
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - name: Install
        run: npm ci
      - name: Build
        run: |
          npm run build --scope textlint-website
          npm run website
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY_WEBSITE }}
          external_repository: textlint/textlint.github.io
          publish_branch: master
          publish_dir: ./website/build/textlint
